Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 900
      MemorySize: 512
      Handler: helloworld.App
      CodeUri: C:\Users\Iris.Perroni\Desktop\teste\HelloWord\HelloWorldFunction
      Runtime: java11
      Architectures:
        - x86_64